# Generated by Django 3.1.3 on 2020-11-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatsheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatsheet',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
