# Generated by Django 3.1.3 on 2020-11-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatsheets', '0002_cheatsheet_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheatsheet',
            name='url',
        ),
        migrations.AddField(
            model_name='cheatsheet',
            name='pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
