# Generated by Django 3.1.3 on 2020-11-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatsheets', '0003_auto_20201130_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatsheet',
            name='pdf',
            field=models.FileField(blank=True, upload_to='cheatsheets/pdfs/'),
        ),
    ]
